trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'  
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled

  - script: mvn clean install
    displayName: 'Build the application'



