trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '8'  # Set the Java version to 8

  - script: mvn clean pakage
    displayName: 'Build the application'



